# -*- coding: utf-8 -*-
"""Copy of Deteccao_de_Fraudes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wP0eG_TsEyxREnfy-n92fh62n8_zl2kk

Importação dos dados
"""

import pandas as pd

url ="https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"

df = pd.read_csv(url)

df.head()

"""Problema: Classificação Desbalanceada"""

# Encontrar a proporção de cada tipo de transação(classe) no conjunto das amostras
# idenfificamos uma classe(fraudes) muito pequeno em relação a outra classe(não fraudes). Isto representa um desbalanceamento do
# dataset de modo que o modelo treinado tenderá a responder não é fraude ficando comprometida a acurácia do modelo.

df['Class'].value_counts(normalize=True)

"""Feature Engineering"""

# features são as variáveis: time, v1 - v28, amout
# criar ou transformar variáveis para melhor que o modelo possa ter melhor compreensão das informações
import numpy as np

# Return the natural logarithm of one plus the input array, element-wise. log(1 + x)
# finalidade melhor balanceamento das amostras

df["Amout_log"] = np.log1p(df["Amount"])

# para evitar valor igual a zero,
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# resultado: tranforma valor em escala, média igual a zero e desvio padrão igual a 1
df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])

from sklearn.model_selection import train_test_split
x = df.drop(["Class"], axis=1) # retira a coluna Class do conjunto x
y = df["Class"] # atribui a coluna Class(target) à variável y, com ela poderemos identificar se a operação é fraude ou não

# separar dados em treino e test
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.3,random_state=42)

"""Logistic Regression"""

from sklearn.linear_model import LogisticRegression
# modelo de classificação
# aplicação no caso: prever se operação é fraude ou não

model = LogisticRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

# Aviso que o modelo porque o número de iterações chegou no limite.
#
# /usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
# STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.
# Increase the number of iterations (max_iter) or scale the data as shown in:
#     https://scikit-learn.org/stable/modules/preprocessing.html
# Please also refer to the documentation for alternative solver options:
#     https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
#

from sklearn.metrics import classification_report
# averguar resultados de predição do modelo
print(classification_report(y_test, y_pred))


#    Classe 1 representa fraudes
#       precision    recall  f1-score   support
# 0          1.00      1.00      1.00     85295
# 1          0.84      0.66      0.74       148
#
# precision 84%, f1(média harmônica) 0,74%
# recall 0,66% eram fraudes reais, indica problema no modelo pois está deixando passar fraudes

"""ROC Curve"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_probs = model.predict_proba(x_test)[:,1]
fpr, tpr, _ = roc_curve(y_test, y_pred)

plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("False positive rate")
plt.ylabel("True positive rate")
plt.show()

print("AUC: ", roc_auc_score(y_test, y_probs))

"""Precision Recall Curve"""

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_test, y_probs)

plt.plot(recall, precision)
plt.title("Precision Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

"""Balanceamento de Dados"""

# Undersampling
fraudes = df[df['Class'] == 1 ]
normais = df[df['Class'] == 0 ].sample(len(fraudes), random_state=42)

df_under = pd.concat([fraudes,normais])

# Oversampling
from imblearn.over_sampling import SMOTE

smote = SMOTE()

x_res, y_res = smote.fit_resample(x, y)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
  )

rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)

print(classification_report(y_test, y_pred_rf))

"""Pipeline"""

from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])
pipeline.fit(x_train, y_train)
y_pred = pipeline.predict(x_test)

threshold = 0.3

y_pred_custom = (y_pred > threshold).astype(int)

print(classification_report(y_test, y_pred_custom))

"""Modelo Avançado - XGBoost"""

from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight=10,
    eval_metric="logloss"
)
xgb.fit(x_train, y_train)

y_pred_sgb = xgb.predict(x_test)

print(classification_report(y_test, y_pred_sgb))

"""Importância das Variáveis"""

importancias = xgb.feature_importances_

plt.bar(range(len(importancias)), importancias)
plt.title("Importância das Variáveis")
plt.show()

"""Ajuste de hiperparâmetros"""

from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [3, 5]
}

grid = GridSearchCV(
    XGBClassifier(eval_metric="logloss"),
        param_grid=param_grid,
        scoring="recall",
        cv=3
)
grid.fit(x_train, y_train)

print("Melhor modelo: ", grid.best_params_)

"""Explicabilidade (SHAP)"""

import shap

explainer = shap.Explainer(xgb)

shap_values = explainer(x_test[:100])

shap.plots.bar(shap_values)